// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AmuLab.Core.Entities;
using DapperExtensions.Mapper;

namespace AmuLab.Repository.Mapper
{

    public partial class TGNRTR_MEDIAMapper : ClassMapper<TGNRTR_MEDIAEntity>
    {

		public TGNRTR_MEDIAMapper()
		{
			base.Table("TGNRTR_MEDIA");

 
		    Map(f => f.Id).Key(KeyType.Identity);
		}


    }
}
#pragma warning restore 1591
