// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AmuLab.Core.Entities;
using DapperExtensions.Mapper;

namespace AmuLab.Repository.Mapper
{

    public partial class TMEDIA_FLNGMapper : ClassMapper<TMEDIA_FLNGEntity>
    {

		public TMEDIA_FLNGMapper()
		{
			base.Table("TMEDIA_FLNG");

			Map(f => f.MEDIA_ID).Column("MEDIA_ID");
			Map(f => f.FLNG_TCD).Column("FLNG_TCD");
			Map(f => f.FLNG_ID).Column("FLNG_ID");
			Map(f => f.AUTH_ID).Column("AUTH_ID");
			Map(f => f.AUTH_NM).Column("AUTH_NM");
			Map(f => f.FLNG_SCD).Column("FLNG_SCD");
			Map(f => f.FLNG_CDT).Column("FLNG_CDT");
			Map(f => f.FLNG_BY_MBER_IND).Column("FLNG_BY_MBER_IND");
			Map(f => f.SHRD_KEY).Column("SHRD_KEY");
		}


    }
}
#pragma warning restore 1591
