// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AmuLab.Core.Entities;
using DapperExtensions.Mapper;

namespace AmuLab.Repository.Mapper
{

    public partial class TMEDIA_TAG_MBERMapper : ClassMapper<TMEDIA_TAG_MBEREntity>
    {

		public TMEDIA_TAG_MBERMapper()
		{
			base.Table("TMEDIA_TAG_MBER");

			Map(f => f.MEDIA_ID).Column("MEDIA_ID");
			Map(f => f.TAG_MBER_ID).Column("TAG_MBER_ID");
			Map(f => f.MBER_ID).Column("MBER_ID");
			Map(f => f.MBER_NM).Column("MBER_NM");
			Map(f => f.SHRD_KEY).Column("SHRD_KEY");
		}


    }
}
#pragma warning restore 1591
