// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AmuLab.Core.Entities;
using DapperExtensions.Mapper;

namespace AmuLab.Repository.Mapper
{

    public partial class TMEDIA_SHR_RECMapper : ClassMapper<TMEDIA_SHR_RECEntity>
    {

		public TMEDIA_SHR_RECMapper()
		{
			base.Table("TMEDIA_SHR_REC");

			Map(f => f.SHR_ID).Column("SHR_ID");
			Map(f => f.MEDIA_ID).Column("MEDIA_ID");
			Map(f => f.SHR_TO_ENTY_ID).Column("SHR_TO_ENTY_ID");
			Map(f => f.SHR_BY_ENTY_ID).Column("SHR_BY_ENTY_ID");
			Map(f => f.SHR_BY_ENTY_NM).Column("SHR_BY_ENTY_NM");
			Map(f => f.SHR_TCD).Column("SHR_TCD");
			Map(f => f.SHR_SCD).Column("SHR_SCD");
			Map(f => f.SHR_CDT).Column("SHR_CDT");
			Map(f => f.SHRD_KEY).Column("SHRD_KEY");
		}


    }
}
#pragma warning restore 1591
