// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AmuLab.Core.Entities;
using DapperExtensions.Mapper;

namespace AmuLab.Repository.Mapper
{

    public partial class TMEDIA_RPRTMapper : ClassMapper<TMEDIA_RPRTEntity>
    {

		public TMEDIA_RPRTMapper()
		{
			base.Table("TMEDIA_RPRT");

			Map(f => f.MEDIA_ID).Column("MEDIA_ID");
			Map(f => f.RPRT_ID).Column("RPRT_ID");
			Map(f => f.SHRD_KEY).Column("SHRD_KEY");
			Map(f => f.TOT_LIKE_CNTR).Column("TOT_LIKE_CNTR");
			Map(f => f.TOT_UNLIKE_CNTR).Column("TOT_UNLIKE_CNTR");
			Map(f => f.TOT_CMNT_CNTR).Column("TOT_CMNT_CNTR");
			Map(f => f.TOT_SHR_CNTR).Column("TOT_SHR_CNTR");
			Map(f => f.TOT_FVRT_CNTR).Column("TOT_FVRT_CNTR");
			Map(f => f.TOT_VIEW_CNTR).Column("TOT_VIEW_CNTR");
			Map(f => f.TOT_CLCK_CNTR).Column("TOT_CLCK_CNTR");
			Map(f => f.LOVE_CNTR).Column("LOVE_CNTR");
			Map(f => f.HAHA_CNTR).Column("HAHA_CNTR");
			Map(f => f.WOW_CNTR).Column("WOW_CNTR");
			Map(f => f.SAD_CNTR).Column("SAD_CNTR");
		}


    }
}
#pragma warning restore 1591
