// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AmuLab.Core.Entities;
using DapperExtensions.Mapper;

namespace AmuLab.Repository.Mapper
{

    public partial class TMEDIA_CLCKMapper : ClassMapper<TMEDIA_CLCKEntity>
    {

		public TMEDIA_CLCKMapper()
		{
			base.Table("TMEDIA_CLCK");

			Map(f => f.MEDIA_ID).Column("MEDIA_ID");
			Map(f => f.CLCK_ID).Column("CLCK_ID");
			Map(f => f.CLCK_ENTY_ID).Column("CLCK_ENTY_ID");
			Map(f => f.CLCK_ENTY_NM).Column("CLCK_ENTY_NM");
			Map(f => f.ENTY_IP_ADDR).Column("ENTY_IP_ADDR");
			Map(f => f.ENTY_DVC_INFO).Column("ENTY_DVC_INFO");
			Map(f => f.CLCK_BY_MBER_IND).Column("CLCK_BY_MBER_IND");
			Map(f => f.CLCK_BY_ANYM_IND).Column("CLCK_BY_ANYM_IND");
			Map(f => f.CLCK_DT).Column("CLCK_DT");
			Map(f => f.SHRD_KEY).Column("SHRD_KEY");
		}


    }
}
#pragma warning restore 1591
