// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AmuLab.Core.Entities;
using DapperExtensions.Mapper;

namespace AmuLab.Repository.Mapper
{

    public partial class TMEDIAMapper : ClassMapper<TMEDIAEntity>
    {

		public TMEDIAMapper()
		{
			base.Table("TMEDIA");

			Map(f => f.MEDIA_ID).Column("MEDIA_ID");
			Map(f => f.SHRD_KEY).Column("SHRD_KEY");
			Map(f => f.MEDIA_NM).Column("MEDIA_NM");
			Map(f => f.MEDIA_FIL_TY).Column("MEDIA_FIL_TY");
			Map(f => f.MEDIA_EXTN).Column("MEDIA_EXTN");
			Map(f => f.MEDIA_SIZE_NBR).Column("MEDIA_SIZE_NBR");
			Map(f => f.MEDIA_LOC_PATH).Column("MEDIA_LOC_PATH");
			Map(f => f.MEDIA_EXTR_ID).Column("MEDIA_EXTR_ID");
			Map(f => f.MEDIA_THUMB_NM).Column("MEDIA_THUMB_NM");
			Map(f => f.MEDIA_TCD).Column("MEDIA_TCD");
			Map(f => f.MEDIA_SCD).Column("MEDIA_SCD");
			Map(f => f.MEDIA_PVCY_TCD).Column("MEDIA_PVCY_TCD");
			Map(f => f.OWNR_ID).Column("OWNR_ID");
			Map(f => f.PIN_IND).Column("PIN_IND");
			Map(f => f.LAST_CMNT_ID).Column("LAST_CMNT_ID");
			Map(f => f.SHR_OFF_IND).Column("SHR_OFF_IND");
			Map(f => f.CMNT_OFF_IND).Column("CMNT_OFF_IND");
			Map(f => f.FLNG_OFF_IND).Column("FLNG_OFF_IND");
			Map(f => f.MEDIA_CDT).Column("MEDIA_CDT");
			Map(f => f.MEDIA_DEL_DT).Column("MEDIA_DEL_DT");
			Map(f => f.DEL_BY_ENTY_ID).Column("DEL_BY_ENTY_ID");
			Map(f => f.DEL_BY_ADM_IND).Column("DEL_BY_ADM_IND");
			Map(f => f.CLCK_LINK_IND).Column("CLCK_LINK_IND");
			Map(f => f.CLCK_LINK_EXTR_IND).Column("CLCK_LINK_EXTR_IND");
			Map(f => f.CLCK_LINK_URL).Column("CLCK_LINK_URL");
			Map(f => f.CLCK_LINK_LBL).Column("CLCK_LINK_LBL");
			Map(f => f.ENTY_IP_ADDR).Column("ENTY_IP_ADDR");
			Map(f => f.LIKE_CNTR).Column("LIKE_CNTR");
			Map(f => f.UNLIKE_CNTR).Column("UNLIKE_CNTR");
			Map(f => f.CMNT_CNTR).Column("CMNT_CNTR");
			Map(f => f.SHR_CNTR).Column("SHR_CNTR");
			Map(f => f.FVRT_CNTR).Column("FVRT_CNTR");
			Map(f => f.VIEW_CNTR).Column("VIEW_CNTR");
			Map(f => f.CLCK_CNTR).Column("CLCK_CNTR");
			Map(f => f.PBLISH_ON_TCD).Column("PBLISH_ON_TCD");
			Map(f => f.POST_ID).Column("POST_ID");
			Map(f => f.MEDIA_TITLE).Column("MEDIA_TITLE");
			Map(f => f.MEDIA_DESC).Column("MEDIA_DESC");
		}


    }
}
#pragma warning restore 1591
