// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AmuLab.Core.Entities;
using DapperExtensions.Mapper;

namespace AmuLab.Repository.Mapper
{

    public partial class TMEDIA_FVRTMapper : ClassMapper<TMEDIA_FVRTEntity>
    {

		public TMEDIA_FVRTMapper()
		{
			base.Table("TMEDIA_FVRT");

			Map(f => f.ENTY_ID).Column("ENTY_ID");
			Map(f => f.MEDIA_ID).Column("MEDIA_ID");
			Map(f => f.ENTY_NM).Column("ENTY_NM");
			Map(f => f.FRVT_SCD).Column("FRVT_SCD");
			Map(f => f.FRVT_CDT).Column("FRVT_CDT");
			Map(f => f.SHRD_KEY).Column("SHRD_KEY");
		}


    }
}
#pragma warning restore 1591
