// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AmuLab.Core.Entities;
using DapperExtensions.Mapper;

namespace AmuLab.Repository.Mapper
{

    public partial class TMEDIA_VIEWMapper : ClassMapper<TMEDIA_VIEWEntity>
    {

		public TMEDIA_VIEWMapper()
		{
			base.Table("TMEDIA_VIEW");

			Map(f => f.MEDIA_ID).Column("MEDIA_ID");
			Map(f => f.VIEW_ID).Column("VIEW_ID");
			Map(f => f.VIEWER_ID).Column("VIEWER_ID");
			Map(f => f.VIEWER_NM).Column("VIEWER_NM");
			Map(f => f.VIEWER_IP_ADDR).Column("VIEWER_IP_ADDR");
			Map(f => f.VIEWER_DVC_INFO).Column("VIEWER_DVC_INFO");
			Map(f => f.VIEW_BY_MBER_IND).Column("VIEW_BY_MBER_IND");
			Map(f => f.VIEW_BY_ANYM_IND).Column("VIEW_BY_ANYM_IND");
			Map(f => f.VIEW_DT).Column("VIEW_DT");
			Map(f => f.SHRD_KEY).Column("SHRD_KEY");
		}


    }
}
#pragma warning restore 1591
