// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;

namespace AmuLab.Core.Entities
{
    public partial class TGNRTR_MEDIAEntity : BaseEntity
    {
        public long ID { get; set;}
    }
}
#pragma warning restore 1591
