// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using AmuLab.Core.Entities;

namespace AmuLab.Core.Entities
{
    public partial class TMEDIA_SHR_RECEntity : BaseEntity
    {
        public long MEDIA_ID { get; set;}
        public long SHR_TO_ENTY_ID { get; set;}
        public long SHR_BY_ENTY_ID { get; set;}
        public string SHR_BY_ENTY_NM { get; set;}
        public string SHR_TCD { get; set;}
        public string SHR_SCD { get; set;}
        public int SHR_CDT { get; set;}
        public string SHRD_KEY { get; set;}
    }
}
#pragma warning restore 1591
