// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;

namespace AmuLab.Core.Entities
{
    public partial class TMEDIA_CLCKEntity : BaseEntity
    {
        public long MEDIA_ID { get; set;}
        public long CLCK_ID { get; set;}
        public long? CLCK_ENTY_ID { get; set;}
        public string CLCK_ENTY_NM { get; set;}
        public string ENTY_IP_ADDR { get; set;}
        public string ENTY_DVC_INFO { get; set;}
        public string CLCK_BY_MBER_IND { get; set;}
        public string CLCK_BY_ANYM_IND { get; set;}
        public int CLCK_DT { get; set;}
        public string SHRD_KEY { get; set;}
    }
}
#pragma warning restore 1591
