// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using AmuLab.Core.Entities;

namespace AmuLab.Core.Entities
{
    public partial class TMEDIA_RPRTEntity : BaseEntity
    {
        public long MEDIA_ID { get; set;}
        public long RPRT_ID { get; set;}
        public string SHRD_KEY { get; set;}
        public int TOT_LIKE_CNTR { get; set;}
        public int TOT_UNLIKE_CNTR { get; set;}
        public int TOT_CMNT_CNTR { get; set;}
        public int TOT_SHR_CNTR { get; set;}
        public int TOT_FVRT_CNTR { get; set;}
        public int TOT_VIEW_CNTR { get; set;}
        public int TOT_CLCK_CNTR { get; set;}
        public int LOVE_CNTR { get; set;}
        public int HAHA_CNTR { get; set;}
        public int WOW_CNTR { get; set;}
        public int SAD_CNTR { get; set;}
    }
}
#pragma warning restore 1591
