// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using AmuLab.Core.Entities;

namespace AmuLab.Core.Entities
{
    public partial class TMEDIA_FLNGEntity : BaseEntity
    {
        public long MEDIA_ID { get; set;}
        public string FLNG_TCD { get; set;}
        public long FLNG_ID { get; set;}
        public long AUTH_ID { get; set;}
        public string AUTH_NM { get; set;}
        public string FLNG_SCD { get; set;}
        public DateTime FLNG_CDT { get; set;}
        public string FLNG_BY_MBER_IND { get; set;}
        public string SHRD_KEY { get; set;}
    }
}
#pragma warning restore 1591
