// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;

namespace AmuLab.Core.Entities
{
    public partial class TMEDIAEntity : BaseEntity
    {
        public long MEDIA_ID { get; set;}
        public string SHRD_KEY { get; set;}
        public string MEDIA_NM { get; set;}
        public string MEDIA_FIL_TY { get; set;}
        public string MEDIA_EXTN { get; set;}
        public int MEDIA_SIZE_NBR { get; set;}
        public string MEDIA_LOC_PATH { get; set;}
        public string MEDIA_EXTR_ID { get; set;}
        public string MEDIA_THUMB_NM { get; set;}
        public string MEDIA_TCD { get; set;}
        public string MEDIA_SCD { get; set;}
        public string MEDIA_PVCY_TCD { get; set;}
        public long OWNR_ID { get; set;}
        public string PIN_IND { get; set;}
        public long LAST_CMNT_ID { get; set;}
        public string SHR_OFF_IND { get; set;}
        public string CMNT_OFF_IND { get; set;}
        public string FLNG_OFF_IND { get; set;}
        public DateTime MEDIA_CDT { get; set;}
        public int MEDIA_DEL_DT { get; set;}
        public int? DEL_BY_ENTY_ID { get; set;}
        public string DEL_BY_ADM_IND { get; set;}
        public string CLCK_LINK_IND { get; set;}
        public string CLCK_LINK_EXTR_IND { get; set;}
        public string CLCK_LINK_URL { get; set;}
        public string CLCK_LINK_LBL { get; set;}
        public string ENTY_IP_ADDR { get; set;}
        public int LIKE_CNTR { get; set;}
        public int UNLIKE_CNTR { get; set;}
        public int CMNT_CNTR { get; set;}
        public int SHR_CNTR { get; set;}
        public int FVRT_CNTR { get; set;}
        public int VIEW_CNTR { get; set;}
        public int CLCK_CNTR { get; set;}
        public string PBLISH_ON_TCD { get; set;}
        public long? POST_ID { get; set;}
        public string MEDIA_TITLE { get; set;}
        public string MEDIA_DESC { get; set;}
    }
}
#pragma warning restore 1591
