// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;

namespace AmuLab.Core.Entities
{
    public partial class TMEDIA_HASHTAGEntity : BaseEntity
    {
        public long HASHTAG_ID { get; set;}
        public long MEDIA_ID { get; set;}
        public string HASHTAG_NM { get; set;}
        public string SHRD_KEY { get; set;}
    }
}
#pragma warning restore 1591
