// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using AmuLab.Core.Entities;

namespace AmuLab.Core.Entities
{
    public partial class TMEDIA_TAG_MBEREntity : BaseEntity
    {
        public long MEDIA_ID { get; set;}
        public long TAG_MBER_ID { get; set;}
        public long MBER_ID { get; set;}
        public string MBER_NM { get; set;}
        public string SHRD_KEY { get; set;}
    }
}
#pragma warning restore 1591
